# Generated by Django 5.2.6 on 2025-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client_referral_completed_at_client_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_seen_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
