# Generated by Django 5.2.6 on 2025-10-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_client_referral_seen_by_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='referral_seen_by_doctor',
            new_name='referral_seen',
        ),
    ]
