# Generated by Django 5.2.6 on 2025-10-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_referral_seen_by_doctor_client_referral_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='referral_seen',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
